### ISSUE TITLE
Transaction table bug in account page

### ISSUE THREAD

**Issue by hanjukim** [terra-project/finder#18]
Page Url: https://finder.terra.money/account/terra1yg5gcx9krjhq0at036uyjg2h0cpxwt5g76ksnl

in Transaction section you can see transactions are not sorted by block and there are also duplications.

We have to make result distinct & sort by block number.

**Comment by s10n** [comment]
388a988 resolved this issue by sorting by timestamp. But, block duplications still exists because we show sender and recipient in one table. So if someone send luna to himself then it will be shown twice. It's not a bug.
