### ISSUE TITLE
Failed transactions seen as success

### ISSUE THREAD

**Issue by hanjukim** [terra-project/finder#20]
Link: https://finder.terra.money/tx/E9B7F9FC2D73749A505CBD8D7CB47A3E60E6E5765283FD01867BFFACFECD2302

Above page shows `Status: success` but the transaction was actually failed. You can see it from: https://lcd.terra.money/txs/E9B7F9FC2D73749A505CBD8D7CB47A3E60E6E5765283FD01867BFFACFECD2302

**Comment by s10n** [comment]
It was hardcoded yet. I will fix it soon.

**Comment by s10n** [comment]
https://finder.terra.money/soju-0007/tx/E9B7F9FC2D73749A505CBD8D7CB47A3E60E6E5765283FD01867BFFACFECD2302
