### ISSUE TITLE
검색 결과 없을 때 error 화면 표시됨

### ISSUE THREAD

**Issue by Freya-Shin** [terra-project/finder#48]
# Summary
검색 결과가 없을 경우 error 500 또는 404 화면 표시됨
# Expected
not found 화면 표시됨
# Environments
* Chain: Columbus-2, Vodka
* OS: Windows
* Platform: Web_Chrome

**Comment by Freya-Shin** [comment]
address 오타 있는 경우 error 500 화면이 표시되고 있습니다.

**Comment by Freya-Shin** [comment]
address 잘못 입력했을 때 아래와 같이 에러 코드가 그대로 노출되고 있습니다. 사용자에게 에러 화면 또는 에러 코드를 보여주는 것은 피하는 게 좋을 것 같은데 확인 부탁드려요. @brianTerra 
![image](https://user-images.githubusercontent.com/52445470/62846693-05bce200-bd0d-11e9-91c2-a52c9017cf71.png)

**Comment by brianTerra** [comment]
@Freya-Shin @CUI-DI 기존 finder 에도 Not found 화면 있었는데요, 그 화면으로 대체하면 될 것 같습니다.

**Comment by Freya-Shin** [comment]
수정 확인했습니다.
