### ISSUE TITLE
[Col1] Claim history > Amount error

### ISSUE THREAD

**Issue by Freya-Shin** [terra-project/finder#55]
# Summary
Validator details > Claim history > 'Amount' is displayed 'NaN'
https://finder-next.cuidi.now.sh/columbus-1/validator/terravaloper1khfcg09plqw84jxy5e7fj6ag4s2r9wqsgm7k94
# Expected
'Amount' should be displayed as numbers.
# Environments
* Chain: Columbus-1
* OS: Windows
* Platform: Web_Chrome
![image](https://user-images.githubusercontent.com/52445470/62860770-41bb6b80-bd3c-11e9-8f9a-14c0f13b5d99.png)

**Comment by algok** [comment]
@CUI-DI 이거 col1에서는 amount 로그가 안남아서 빈어레이로 리턴할게요

**Comment by Freya-Shin** [comment]
This issue is resolved.
